name: CI

on: [push]

jobs:
  build:

    runs-on: [macos]

    steps:
    - uses: actions/checkout@v1
    - name: Run Tests
      uses: maierj/fastlane-action@v1.0.0
      with:
        lane: test
        subdirectory: fastlane
